sudo: enabled
language: python
python: ["3.6"]
before_install:
- openssl aes-256-cbc -K $encrypted_511a9cc1f979_key -iv $encrypted_511a9cc1f979_iv
  -in gdpr-ssh-key.enc -out /tmp/gdpr-ssh-key -d
- sudo apt-get update -qy
- sudo apt-get install -y python3 python3-pip ruby-sass locales rsync
- sudo sh -c 'echo "en_US UTF-8" > /etc/locale.gen'
- sudo locale-gen en_US.UTF-8
- export LANG=en_US.UTF-8
- export LANGUAGE=en_US:en
- export LC_ALL=en_US.UTF-8
- export PYTHONPATH=.:$PYTHONPATH
script: make prod
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^staging|production$"
env:
  global:
  - secure: x18MZXJPAuCgJoj4wEMetFDRQedn8t59XaPM7aFSfHIYg/bym51vOuyTCMFrD+AJzlRcgokyzMRvW0Pr4euMp8sl/nq2VPXk7tYImxr2refHwI3cG6q/rAnmrIfFyYBBRxwz21E+McCtjLFshOazheP2s4peUcsDFb4piZQjXxsBlfdTUnJy28reb1WHhOW/sMLO6pd885Ggw8fTC4lozRQVBpvZ4l+GMKn9d2inJZMuGSzVoQJg1fsS8zZfTuWbRo/r+fUwqzE3hnoAT8bgGlYSaBWwMPtrqSvp9Nbeb0RRCq8uxXkSY3IzLK23s6NZwvRf7xe1Etyj9xhn4mEzDA7TQfkP50vjUIF+F1rWkUShJdf5OcCziNswRWdfEvLaUSr17YKHi/ocNy10mJE4nAaMxUH+0ESjVIMa6coQx9olVDGmy4BdjnnsTkICsQ70ttn/XtTpbFOqDyarVbb7t2ihRK6u6XtQ0iYGVvbgpLtxpgVCTM55gmzffhbEdZXcGjQYD/pJ4pr2LIfUUZTaUKVt5rQFDLODoQMokjU8CGDB94vMeGOfjvSlardlOwRCDokhM8dYuXZNM37xKEphxqPmOyJ0Cv8w0rlqFQeS5oW3+mRPzUQm3aFALVy5sSky4JTuCN9DDP24lFgwwZ1rbVWFmQFzZVevmCT1hg9nUmk=
  - secure: bsokkp1lJAkcNh3rOh3/geaQ05Ji8C7hSQL2x/7YQNTkOnIrLAkSx5mpZTaUooa8/I435FIRRCpJtDa8ASQUnQDGA5kz5Tkm5LuqlAiowjBkicpIUlejykdOZw8PC55dXBTI8D4v7zBE1zEFHODdl4tsATK6PDc9FPJlUj3XsqJxddC++iGKOi193+gGpSMo6L8KDUJ0jU1y9EGcLhGl+6qy9Mhqx1m/Ez0cxmEYMABlr/WKgC47Z7Y6LDe/tcfTLfrMh9poK6DXii2KZTwtyKKgwVlmR19vhofPbrEVENSLVDGwhtBfjpy4WBzODHQ0viZ6VXpxkZtyvTG8sPaGniX3l+e1hll3dHLa/QJ3Mz/VWUt95Ue9e5EYoaO+26wyWZs8BbnDYerXKO5R6kKE5UgUVeB6j85uBjQ5iwSgRnUzVTfYqnxjW/+qLeGkSnMWRaaSi/B19u9BlEymT6hQqotyqpyJV4cd7TWP0mMUHgzO59vh3AS71N4MdkLTFEmwXWnvtE0sfqU36bzAXt1Br9FBQM77E1vAY5f0NbAxHtac1AgQPIG/YaggyJWpBUjBt0jtUHNtfVhkW7zvYM0mJZUXine+vT9XX89qsR7qq87SGGNFqUtI9W22p9v3z1nVahJCq1NgTrZ7hRVO6zAxqvK3HGSJPpSWY1acJmuMrOs=
  - secure: RDBZv3dJD4QUVVZToNksPU2Ej4CYlSePKCvaRjz6FQFo58KaWkXaN7uKV7lmCAuAMrYxhEhE5ibb+ajcnRsZATnK0fL7gTvkdJU2bd7LY1W78ILEIFdqOd/6hG9tzsvFjJijm8ZRHXTxEGJKuO74j2CMI/Sz4ldhmiMvdepXWLXks4a63NAbqRzktFPNin3Sr3zddE878jjxX70N5akmH/3oTtaTEq1KdC6Q9mUja6t+QJ046DLFIc93d67A5oSfFjx4eEk00YG/IFOHNGo2xndaLEt8B37IyhTcSKZP8QFWKPE3lBpF2SPGaz0mc6AIjw+FAVxKolY0nASKE8m4k553Z/b0cR2YwcqnuPLDF+bM600rPPP56RkjS+fUW0SdM1LLbEbkf8NrpxDZlxhmHybItbDFEd65zG4QhS3QDwHwg6/4/MFYcMuqAaRih/kJ8viVWhcBKNnlz5mWleSm3yuNUTPNbNrMKNFaKOwCEHEPeqxFTgTx8DVCvzArY94lFKETlVvRiDD2I1ef2ZfkGgOgU00WE/RBR5Prr/yQcgXlYyawdh8TqzdEZerMDqZkcFvxbZJnvPJ/EaMdFK7IQl/qcyBRubWN4YHKe7G0EnCxeW3vUbTMfCN51n681uNb8ZppFVworxJsb34VIwhOM1LoU2rvFAFvCS3boSk5R3Y=
