name: dpkit-website
blog-path: blog
theme-path: themes/docs
url: http://localhost:8000
context:
  author: 7scientists GmbH
path: /
languages:
  #these pages will be copied to all languages
  $all:
    pages: []
  #english pages
  en:
    $include: site-en.yml
  #german pages
  de:
    $include: site-de.yml
translations:
  $include: translations.yml
builders:
  - name: law-portal
    builder: helpers.law_builder.LawBuilder
repo-url: 'https://github.com/DPKit/gdpr-portal'
